version: "3.7"
# docker exec -it ansible-test_ansible_1 /bin/bash
services: 
  ansible:
    env_file:
      - build.env
    build: 
      context: .
      dockerfile: dockerfile
      args:  
        - ANSIBLE_FILES=${FILES}
        - ANSIBLE_USER=${USER} #set in .env file in same level as docker-compose.yaml
    image: ansible-centos7:latest
    container_name: ansible_runner
    ports:
      - "9022:22"
    volumes: 
      # current user .ssh keys in container for use
      - ~/.ssh/:/home/${USER}/.ssh:ro
      # use variable notation to put items in $HOME 
#     ~ ./folder:/home/${USER}/folder
      - ./kubespray:/home/${USER}/kubespray
      # ansible configuration files and editing outside of container
      #- ./ansible-storage/ansible.cfg:/home/${USER}/ansible.cfg
      #- ./ansible-storage/ansible.log:/home/${USER}/${FILES}/ansible.log
      - ./ansible-storage/:/home/${USER}/${FILES}/
