version: "3.3"
# docker exec -it ansible-test_ansible_1 /bin/bash
services: 
  ansible:
    build: 
      context: .
      dockerfile: dockerfile
      args:  #set in .env file in same level as docker-compose.yaml
        ANSIBLE_FILES: ${FILES}
        ANSIBLE_USER_PASS: ${PASS}
        ANSIBLE_USER: ${ANSIBLE_USER} 
    image: ansible-centos7:latest
    container_name: ansible_runner
    ports:
      - "9022:22"
    volumes: 
      # current user .ssh keys in container for use
      - ~/.ssh/:/home/${ANSIBLE_USER}/.ssh:ro
      # use variable notation to put items in $HOME 
#     ~ ./folder:/home/${USER}/folder
      - ./kubespray:/home/${ANSIBLE_USER}/kubespray
      # ansible configuration files and editing outside of container
      - ./ansible-storage/ansible.cfg:/etc/ansible/ansible.cfg
      - ./ansible-storage/ansible.log:/home/${ANSIBLE_USER}/ansible.log
      - ./ansible-storage/:/home/${ANSIBLE_USER}/${FILES}/
